action:
  name: Timebox Mini action
  description: Do some action on Timebox Mini like new view, volume set, time set...
  fields:

    mac_addr:
      name: MAC address
      description: Bluetooth MAC address of the Timebox
      required: true
      example: "11:75:58:7B:8B:29"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        text:

    action:
      name: Action
      description: The action to make on the timebox
      required: true
      example: "weather"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "weather"
            - "image"
            - "animation"
            - "clock"
            - "set_volume"
            - "set_time"
            - "set_brightness"

    image:
      name: Image name
      description: Name of the image to display for 'image' action
      required: false
      example: "green_check"
      default: "home-assistant-black"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "big_bell_black"
            - "big_bell"
            - "black"
            - "green_check"
            - "home-assistant-black"
            - "home-assistant"
            - "home-black"
            - "home"
            - "hourglass_black"
            - "hourglass_white"
            - "locked_black"
            - "locked"
            - "orange_warning"
            - "red_cross"
            - "small_bell_black"
            - "small_bell"
            - "spanner"
            - "spanner_rev"
            - "spanner_tilted"
            - "spanner_tilted_rev"
            - "unlocked_black"
            - "unlocked"
            - "wifi_no"
            - "wifi"
            - "wifi_no_black"
            - "wifi_black"

    animation:
      name: Animation name
      description: Name of the animation to display for 'animation' action
      required: false
      example: "orange_warning"
      default: "orange_warning"
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        select:
          options:
            - "orange_warning"

    volume:
      name: Audio volume
      description: Audio volume level for 'set_volume' action
      required: false
      example: 8
      default: 4
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        number:
          min: 0
          max: 15
          step: 1
          mode: slider

    brightness:
      name: Brightness
      description: Brightness level for 'set_brightness' action
      required: false
      example: 75
      default: 50
      # Selector (https://www.home-assistant.io/docs/blueprint/selectors/) to control the input UI for this field
      selector:
        number:
          min: 0
          max: 100
          step: 5
          mode: slider
          unit_of_measurement: "%"